### ISSUE TITLE
Here's PKGBUILD for AUR

### ISSUE THREAD

**Issue by mizzunet** [noocsharp/wayclip#1]
Here's PKGBUILD for AUR. I don't know much about maintaining packages in AUR. Or I'd have maintain myself

https://0x0.st/oN8h.txt

**Comment by noocsharp** [comment]
Thanks! There were a few issues I noticed:
- `wayclip` is licensed under ISC, not GPL
- it does not depend on `xdg-utils` or `mailcap`
- it does depend on `wlroots` (or anything that provides the `wlr-data-control` wayland protocol)
- when installing, also give `PREFIX="/usr"`, so it gets installed to the `/usr` namespace instead of `/usr/local`

I personally think it's better if somebody beside me maintains packages in the AUR or other repos. I think maintaining packages in the AUR is pretty straightforward, although I've never done it myself. If you don't want to, I'm sure if people find this useful enough, _somebody_ will eventually package it.

**Comment by mizzunet** [comment]
> If you don't want to. I'm sure if people find this useful enough

I'd like to do that, but I couldn't. I'll try to see how actually it is.

Anyway, here's the modified file https://0x0.st/oNNW.txt

**Comment by noocsharp** [comment]
Since a PKGBUILD for `wayclip` is pretty trivial to write, I'm gonna go ahead and close this. But I appreciate your effort and interest.

**Comment by jirutka** [comment]
FYI, I’ve packaged wayclip for Alpine Linux – [wayclip on pkgs.alpinelinux.org](https://pkgs.alpinelinux.org/packages?name=wayclip).
