### ISSUE TITLE
Cannot paste into Firefox

### ISSUE THREAD

**Issue by ioraff** [noocsharp/wayclip#2]
I am unable to copy from `waycopy` and paste into Firefox. The reverse with `waypaste` works as expected.

**Comment by noocsharp** [comment]
By default, `waycopy` sets the offer type to `text/plain`, which Firefox appears not to accept. If you set the offer type to `STRING` or `UTF8_STRING`, Firefox will accept it:
```
$ echo "test" | waycopy -t STRING
```
In my opinion this is not a `wayclip` problem, because the `wlr-data-control` protocol explicitly states that the offer type should be a mimetype, and `STRING` is not a mimetype.
